### ISSUE TITLE
[SUGGESTION/BUG] The video should work with the layout randomiser

### ISSUE THREAD

**Issue by 5UP3RTH30B4G** [SrRapero720/FancyMenu-Video#5]
The mods would be cool if we can use this functionality of fancy menu, cause rn when you try to make it work it just make a black screen
![image](https://github.com/SrRapero720/FancyMenu-Video/assets/68150571/8eea76cc-dcc4-4ac6-b8e4-fbb05a622863)

**Comment by SrRapero720** [comment]
see #6
