### ISSUE TITLE
[Question] FancyMenu: Video Extension for v3

### ISSUE THREAD

**Issue by NumpaMC** [SrRapero720/FancyMenu-Video#6]
Why you don't support FancyMenu: Video Extension for v3
It great you upgrade Video Extension

**Comment by SrRapero720** [comment]
1. i barely have time
2. keksuccino baely had time to answer me question about FM
3. Keksuccino already confirmed FancyMenu will have video compatibility using watermedia. Theres no ETA for it because is waiting for watermedia v3 (which also has no ETA)

**Comment by SrRapero720** [comment]
Issue got blocked because people got very intense like what happened to spiffyhud.
_but yes, issue is there and its planned: https://github.com/Keksuccino/FancyMenu/issues/685_

i put this here because _i want to avoid people requesting me stuff_
